notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false

environment:
    matrix:
      - PRJ_GEN: "Visual Studio 10 2010 Win64"
        BDIR: msvc2010
      - PRJ_GEN: "Visual Studio 11 2012 Win64"
        BDIR: msvc2012
      - PRJ_GEN: "Visual Studio 12 2013 Win64"
        BDIR: msvc2013
      - PRJ_GEN: "Visual Studio 14 2015 Win64"
        BDIR: msvc2015

build_script:
    - mkdir build.%BDIR% && cd build.%BDIR%
    - set URL=https://raw.githubusercontent.com/horta/zlib.install/master/install.bat
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('%URL%', 'install.bat')"
    - install.bat

test_script:
    - if NOT exist "%programfiles%\zlib\lib\zlib.lib" exit 1
    - if NOT exist "%programfiles%\zlib\bin\zlib.dll" exit 1
    - if NOT exist "%programfiles%\zlib\include\zconf.h" exit 1
    - if NOT exist "%programfiles%\zlib\include\zlib.h" exit 1
